type Service = {
  id: number;
  title: string;
  category: string;
  description: string;
  duration: string;
  price: string;
  image: string;
  popular?: boolean;
  rating: number;
};
const prestationData: Service[] = [
  {
    id: 1,
    title: "Table à Manger Massif",
    category: "Mobilier",
    description: "Table sur mesure en bois massif, finition soignée et robustesse longue durée.",
    duration: "5 - 7 jours",
    price: "13.000 FCFA",
    image: "./../public/table tv.jpg",
    popular: true,
    rating: 4.9,
  },
  {
    id: 2,
    title: "Meuble TV Design",
    category: "Mobilier",
    description: "Meuble bas avec rangements et découpes géométriques complexes.",
    duration: "3 - 5 jours",
    price: "5.000 FCFA",
    image: "./../public/mobilier.jpg",
    rating: 4.8,
  },
  {
    id: 3,
    title: "Banc & Assise Bois",
    category: "Mobilier",
    description: "Assises douces et naturelles pour un intérieur élégant et facile d'entretien.",
    duration: "3 - 4 jours",
    price: "7.000 FCFA",
    image: "./../public/table tv.jpg",
    rating: 4.7,
  },
  {
    id: 4,
    title: "Dressing Sur-Mesure Premium",
    category: "Sur-Mesure",
    description: "Dressing entièrement personnalisé avec matériaux de haute qualité.",
    duration: "8 - 12 jours",
    price: "12.000 FCFA",
    image: "./../public/table tv.jpg",
    popular: true,
    rating: 4.9,
  },
  {
    id: 5,
    title: "Étagères Volumineuses",
    category: "Mobilier",
    description: "Étagères épaisses et volumineuses pour un effet spectaculaire.",
    duration: "3 - 4 jours",
    price: "2.000 FCFA",
    image: "./../public/table tv.jpg",
    rating: 4.6,
  },
  {
    id: 6,
    title: "Lit Bois Sans Assemblage Apparent",
    category: "Mobilier",
    description: "Structure de lit sans fixations visibles pour plus de confort et d'élégance.",
    duration: "5 - 7 jours",
    price: "15.000 FCFA",
    image: "./../public/mobilier.jpg",
    popular: true,
    rating: 4.9,
  },
  {
    id: 7,
    title: "Buffet Style Bohème",
    category: "Mobilier",
    description: "Buffet léger et volumineux avec un rendu bohème chic.",
    duration: "4 - 6 jours",
    price: "10.000 FCFA",
    image: "./../public/table tv.jpg",
    rating: 4.8,
  },
  {
    id: 8,
    title: "Meuble Technique Sur-Mesure",
    category: "Sur-Mesure",
    description: "Réalisation sur mesure en bois massif ou matériaux composites.",
    duration: "4 - 6 jours",
    price: "11.000 FCFA",
    image: "./../public/table tv.jpg",
    rating: 4.7,
  },
  {
    id: 9,
    title: "Restauration & Renforcement de Meuble",
    category: "Rénovation",
    description: "Restauration intensive avec traitement et renforcement structurel.",
    duration: "1 - 2 jours",
    price: "9.000 FCFA",
    image: "./../public/table tv.jpg",
    rating: 4.8,
  },
  {
    id: 10,
    title: "Pose de Verrière Style Atelier",
    category: "Sur-Mesure",
    description: "Pose de verrière décorative sur mesure avec personnalisation.",
    duration: "3 - 4 jours",
    price: "12.000 FCFA",
    image: "./../public/table tv.jpg",
    popular: true,
    rating: 4.9,
  },
  {
    id: 11,
    title: "Extension de Terrasse Bois",
    category: "Extérieur",
    description: "Ajout de surface et volume avec structure en bois traité.",
    duration: "5 - 7 jours",
    price: "170.000 FCFA",
    image: "./../public/table tv.jpg",
    rating: 4.7,
  },
  {
    id: 12,
    title: "Étagères Mi-Hauteur",
    category: "Mobilier",
    description: "Étagères mi-hautes élégantes et légères.",
    duration: "4 - 5 jours",
    price: "10.000 FCFA",
    image: "./../public/table tv.jpg",
    rating: 4.6,
  },
  {
    id: 13,
    title: "Meuble avec Incrustations & Marqueterie",
    category: "Mobilier",
    description: "Meubles décorés avec incrustations, marqueterie et accessoires.",
    duration: "4 - 6 jours",
    price: "11.000 FCFA",
    image: "./../public/table tv.jpg",
    rating: 4.8,
  },
  {
    id: 14,
    title: "Traitement Bois Luxe",
    category: "Rénovation",
    description: "Traitement personnalisé avec huiles rares et produits précieux.",
    duration: "1 jour",
    price: "36.000 FCFA",
    image: "/soin/s1.jpg",
    rating: 4.5,
  },
  {
    id: 15,
    title: "Pose de Lambris Naturel",
    category: "Rénovation",
    description: "Pose de lambris en bois naturel ou composite.",
    duration: "3 - 5 jours",
    price: "11.000 FCFA",
    image: "./../public/table tv.jpg",
    rating: 4.6,
  },
  {
    id: 16,
    title: "Mobilier Style Traditionnel Sculpté",
    category: "Mobilier",
    description: "Style traditionnel avec motifs authentiques sculptés à la main.",
    duration: "4 - 6 jours",
    price: "15.000 FCFA",
    image: "./../public/table tv.jpg",
    rating: 4.7,
  },
  {
    id: 17,
    title: "Teinture + Assemblage Sur-Mesure",
    category: "Sur-Mesure",
    description: "Teinture professionnelle et assemblage entièrement sur mesure.",
    duration: "5 - 7 jours",
    price: "157.000 FCFA",
    image: "./../public/table tv.jpg",
    rating: 4.8,
  },
  {
    id: 18,
    title: "Retouche & Réajustement Mobilier",
    category: "Rénovation",
    description: "Retouche et réajustement de mobilier existant.",
    duration: "2 - 4 jours",
    price: "59.000 FCFA",
    image: "./../public/table tv.jpg",
    rating: 4.5,
  },
  {
    id: 19,
    title: "Mobilier Enfant (Chambre)",
    category: "Mobilier",
    description: "Mobilier adapté aux enfants avec finitions sécurisées et arrondies.",
    duration: "2 - 3 jours",
    price: "49.000 FCFA",
    image: "./../public/table tv.jpg",
    rating: 4.9,
  },
  {
    id: 20,
    title: "Traitement Anti-Insectes Xylophages",
    category: "Rénovation",
    description: "Traitement renforçant contre les insectes et l'humidité.",
    duration: "1 jour",
    price: "6.000 FCFA",
    image: "/soin/s2.jpg",
    rating: 4.7,
  },
  {
    id: 21,
    title: "Meuble Fibres & Cannage Naturel",
    category: "Mobilier",
    description: "Meuble avec cannage et fibres naturelles pour un volume et une texture unique.",
    duration: "4 - 6 jours",
    price: "8.000 FCFA",
    image: "./../public/table tv.jpg",
    rating: 4.6,
  },
  {
    id: 22,
    title: "Pose d'Éléments Modulables",
    category: "Sur-Mesure",
    description: "Éléments modulaires amovibles pour un aménagement rapide.",
    duration: "1 - 2 jours",
    price: "9.000 FCFA",
    image: "./../public/table tv.jpg",
    rating: 4.5,
  },
  {
    id: 23,
    title: "Plan de Travail Fin & Compact",
    category: "Cuisines",
    description: "Plans de travail fins et compacts avec finition soignée.",
    duration: "5 - 7 jours",
    price: "7.000 FCFA",
    image: "./../public/table tv.jpg",
    rating: 4.7,
  },
  {
    id: 24,
    title: "Traitement Vernis Naturel",
    category: "Rénovation",
    description: "Traitement au vernis naturel pour lisser et protéger le bois.",
    duration: "1 jour",
    price: "13.000 FCFA",
    image: "/soin/s3.jpg",
    rating: 4.8,
  },
  {
    id: 25,
    title: "Meuble Mixte (Bois + Métal)",
    category: "Sur-Mesure",
    description: "Création mixte combinant plusieurs matériaux et techniques.",
    duration: "5 - 6 jours",
    price: "12.000 FCFA",
    image: "./../public/table tv.jpg",
    rating: 4.8,
  },
  {
    id: 26,
    title: "Retouche Agencement Cuisine",
    category: "Cuisines",
    description: "Ajustement et entretien d'agencement de cuisine.",
    duration: "1 jour",
    price: "46.000 FCFA",
    image: "/perruques/p1.jpg",
    rating: 4.6,
  },
  {
    id: 27,
    title: "Pergola Style Moderne",
    category: "Extérieur",
    description: "Style moderne et structuré pour vos aménagements extérieurs.",
    duration: "4 - 6 jours",
    price: "10.000 FCFA",
    image: "./../public/table tv.jpg",
    rating: 4.7,
  },
  {
    id: 28,
    title: "Finition Brillance & Protection",
    category: "Rénovation",
    description: "Finition illuminatrice pour une brillance exceptionnelle du bois.",
    duration: "1 jour",
    price: "3.000 FCFA",
    image: "/soin/s4.jpg",
    rating: 4.6,
  },
  {
    id: 29,
    title: "Mobilier Compact Chic",
    category: "Mobilier",
    description: "Mobilier compact moderne et sophistiqué pour petits espaces.",
    duration: "3 - 4 jours",
    price: "72.000 FCFA",
    image: "./../public/table tv.jpg",
    rating: 4.5,
  },
  {
    id: 30,
    title: "Forfait Aménagement Complet",
    category: "Sur-Mesure",
    description: "Prestation complète : conception, fabrication et pose sur site.",
    duration: "6 - 8 jours",
    price: "5.000 FCFA",
    image: "/soin/s7.jpg",
    popular: true,
    rating: 5.0,
  },
  {
    id: 31,
    title: "Forfait Rénovation Complète",
    category: "Rénovation",
    description: "Prestation complète : diagnostic, traitement et finition sur site.",
    duration: "6 - 8 jours",
    price: "5.000 FCFA",
    image: "/soin/s5.jpg",
    popular: true,
    rating: 5.0,
  },
  {
    id: 32,
    title: "Portes & Fenêtres Sur-Mesure",
    category: "Sur-Mesure",
    description: "Prestation complète : conception, fabrication et pose de portes et fenêtres.",
    duration: "6 - 8 jours",
    price: "35.000 FCFA",
   image: "/perruques/p2.jpg",
    popular: true,
    rating: 5.0,
  },
];

export default prestationData;