type Service = {
  id: number;
  title: string;
  category: string;
  description: string;
  duration: string;
  price: string;
  image: string;
  popular?: boolean;
  rating: number;
};
const prestationData: Service[] = [
  {
    id: 1,
    title: "Box Braids Longues",
    category: "Tresses",
    description: "Tresses classiques avec mèches premium, finition parfaite et tenue longue durée.",
    duration: "5h - 7h",
    price: "13.000 FCFA",
    image: "../public/women/1.jpg",
    popular: true,
    rating: 4.9,
  },
  {
    id: 2,
    title: "Cornrows Design",
    category: "Tresses",
    description: "Nattes collées avec motifs géométriques complexes.",
    duration: "3h30 - 5h",
    price: "5.000 FCFA",
    image: "../public/women/f11.jpg",
    rating: 4.8,
  },
  {
    id: 3,
    title: "Twists / Vanilles",
    category: "Tresses",
    description: "Twists doux et naturels pour un look élégant et facile d'entretien.",
    duration: "3h - 4h30",
    price: "7.000 FCFA",
    image: "../public/women/2.jpg",
    rating: 4.7,
  },
  {
    id: 4,
    title: "Fausses Locks (Faux Locs)",
    category: "Tresses",
    description: "Locks temporaires ultra-réalistes avec mèches de haute qualité.",
    duration: "6h - 8h",
    price: "12.000 FCFA",
    image: "../public/women/f12.jpg",
    popular: true,
    rating: 4.9,
  },
  {
    id: 5,
    title: "Tresses Jumbo",
    category: "Tresses",
    description: "Tresses épaisses et volumineuses pour un effet spectaculaire.",
    duration: "3h - 4h30",
    price: "2.000 FCFA",
    image: "../public/women/13.jpg",
    rating: 4.6,
  },
  {
    id: 6,
    title: "Knotless Box Braids",
    category: "Tresses",
    description: "Box Braids sans nœuds à la racine pour plus de confort.",
    duration: "5h - 7h",
    price: "15.000 FCFA",
    image: "../public/women/4.jpg",
    popular: true,
    rating: 4.9,
  },
  {
    id: 7,
    title: "Passion Twists",
    category: "Tresses",
    description: "Twists légers et volumineux avec un rendu bohème chic.",
    duration: "4h - 5h30",
    price: "10.000 FCFA",
    image: "../public/women/5.jpg",
    rating: 4.8,
  },
  {
    id: 8,
    title: "Tresses Crochets (Crochet Braids)",
    category: "Tresses",
    description: "Technique au crochet avec cheveux synthétiques ou naturels.",
    duration: "4h - 6h",
    price: "11.000 FCFA",
    image: "../public/women/6.jpg",
    rating: 4.7,
  },
  {
    id: 9,
    title: "Soin Profond + Reconstruction",
    category: "Soins",
    description: "Soin intensif avec protéines et hydratation profonde.",
    duration: "1h45",
    price: "9.000 FCFA",
    image: "../public/women/7.jpg",
    rating: 4.8,
  },
  {
    id: 10,
    title: "Pose de Perruque HD Lace",
    category: "Extensions",
    description: "Pose de perruque lace frontale invisible avec personnalisation.",
    duration: "3h - 4h30",
    price: "12.000 FCFA",
    image: "../public/women/8.jpg",
    popular: true,
    rating: 4.9,
  },
  {
    id: 11,
    title: "Extensions de Tresses",
    category: "Extensions",
    description: "Ajout de longueur et volume avec tresses protectrices.",
    duration: "5h - 7h",
    price: "170.000 FCFA",
    image: "../public/women/9.jpg",
    rating: 4.7,
  },
  {
    id: 12,
    title: "Braids Mi-Longues",
    category: "Tresses",
    description: "Tresses mi-longues élégantes et légères.",
    duration: "4h - 5h",
    price: "10.000 FCFA",
    image: "../public/women/10.jpg",
    rating: 4.6,
  },
  {
    id: 13,
    title: "Tresses avec Perles & Accessoires",
    category: "Tresses",
    description: "Tresses décorées avec perles, bijoux et accessoires.",
    duration: "4h30 - 6h",
    price: "11.000 FCFA",
    image: "../public/women/11.jpg",
    rating: 4.8,
  },
  {
    id: 14,
    title: "Masque Capillaire Luxe",
    category: "Soins",
    description: "Masque personnalisé avec huiles rares et actifs précieux.",
    duration: "1h15",
    price: "36.000 FCFA",
    image: "../public/soin/s1.jpg",
    rating: 4.5,
  },
  {
    id: 15,
    title: "Weave / Pose de Tissages",
    category: "Extensions",
    description: "Pose de tissages naturels ou synthétiques.",
    duration: "3h - 5h",
    price: "11.000 FCFA",
    image: "../public/women/13.jpg",
    rating: 4.6,
  },
  {
    id: 16,
    title: "Tresses Fulani",
    category: "Tresses",
    description: "Style traditionnel Fulani avec motifs authentiques.",
    duration: "4h - 6h",
    price: "15.000 FCFA",
    image: "../public/women/14.jpg",
    rating: 4.7,
  },
  {
    id: 17,
    title: "Coloration + Tresses",
    category: "Coloration",
    description: "Coloration professionnelle + pose de tresses.",
    duration: "5h - 7h",
    price: "157.000 FCFA",
    image: "../public/women/15.jpg",
    rating: 4.8,
  },
  {
    id: 18,
    title: "Retouche Box Braids",
    category: "Entretien",
    description: "Retouche et réajustement des tresses existantes.",
    duration: "2h30 - 4h",
    price: "59.000 FCFA",
    image: "../public/women/16.jpg",
    rating: 4.5,
  },
  {
    id: 19,
    title: "Tresses Enfant (6-12 ans)",
    category: "Enfants",
    description: "Tresses adaptées aux enfants avec soin particulier.",
    duration: "2h - 3h",
    price: "49.000 FCFA",
    image: "../public/women/17.jpg",
    rating: 4.9,
  },
  {
    id: 20,
    title: "Soin Anti-Chute",
    category: "Soins",
    description: "Traitement renforçant contre la chute de cheveux.",
    duration: "1h30",
    price: "6.000 FCFA",
    image: "../public/soin/s2.jpg",
    rating: 4.7,
  },
  {
    id: 21,
    title: "Braids avec Laine",
    category: "Tresses",
    description: "Tresses avec laine pour volume et texture unique.",
    duration: "4h - 6h",
    price: "8.000 FCFA",
    image: "../public/women/19.jpg",
    rating: 4.6,
  },
  {
    id: 22,
    title: "Pose de Clip-Ins",
    category: "Extensions",
    description: "Extensions temporaires à clips pour un volume instantané.",
    duration: "1h30 - 2h30",
    price: "9.000 FCFA",
    image: "../public/women/20.jpg",
    rating: 4.5,
  },
  {
    id: 23,
    title: "Tresses Sénégalaises",
    category: "Tresses",
    description: "Tresses fines et serrées style sénégalais.",
    duration: "5h - 7h",
    price: "7.000 FCFA",
    image: "../public/women/21.jpg",
    rating: 4.7,
  },
  {
    id: 24,
    title: "Soins Kératine",
    category: "Soins",
    description: "Traitement à la kératine pour lisser et renforcer.",
    duration: "2h30",
    price: "13.000 FCFA",
    image: "../public/soin/s3.jpg",
    rating: 4.8,
  },
  {
    id: 25,
    title: "Tresses Mixtes (Braids + Twists)",
    category: "Tresses",
    description: "Création mixte combinant plusieurs techniques.",
    duration: "5h - 6h30",
    price: "12.000 FCFA",
    image: "../public/women/23.jpg",
    rating: 4.8,
  },
  {
    id: 26,
    title: "Retouche Perruque",
    category: "Entretien",
    description: "Ajustement et entretien de perruque.",
    duration: "1h30",
    price: "46.000 FCFA",
    image: "../public/women/24.jpg",
    rating: 4.6,
  },
  {
    id: 27,
    title: "Braids avec Rasta",
    category: "Tresses",
    description: "Style rasta moderne et structuré.",
    duration: "4h30 - 6h",
    price: "10.000 FCFA",
    image: "../public/women/25.jpg",
    rating: 4.7,
  },
  {
    id: 28,
    title: "Soin Brillance & Hydratation",
    category: "Soins",
    description: "Soin illuminateur pour une brillance exceptionnelle.",
    duration: "1h",
    price: "3.000 FCFA",
    image: "../public/soin/s4.jpg",
    rating: 4.6,
  },
  {
    id: 29,
    title: "Tresses Courtes Chic",
    category: "Tresses",
    description: "Tresses courtes modernes et sophistiquées.",
    duration: "3h - 4h",
    price: "72.000 FCFA",
    image: "../public/women/1.jpg",
    rating: 4.5,
  },
  {
    id: 30,
    title: "Forfait Mariage",
    category: "Soins",
    description: "Prestation complète pour mariée : tresses + coiffure + maquillage.",
    duration: "6h - 8h",
    price: "5.000 FCFA",
    image: "../public/soin/s7.jpg",
    popular: true,
    rating: 5.0,
  },
  {
    id: 31,
    title: "Forfait Mariage",
    category: "Soins",
    description: "Prestation complète pour mariée : tresses + coiffure + maquillage.",
    duration: "6h - 8h",
    price: "5.000 FCFA",
    image: "../public/soin/s5.jpg",
    popular: true,
    rating: 5.0,
  },
  {
    id: 32,
    title: "Forfait Mariage",
    category: "Soins",
    description: "Prestation complète pour mariée : tresses + coiffure + maquillage.",
    duration: "6h - 8h",
    price: "5.000 FCFA",
   image: "../public/soin/s6.jpg",
    popular: true,
    rating: 5.0,
  },
];

export default prestationData;
